config/routes.rb
Checkn::Application.routes.draw do
  namespace :admin do
    resources :news, :only => [:index, :new, :show, :edit, :destroy, :create, :update]
    resources :maps, :only => [:index]
    resources :codes, :only => [:index, :new, :show, :edit, :destroy, :create, :update]
    resources :device_photos, :only => [:index, :new, :destroy, :create]
    root :to => "news#index"
  end

  devise_for :users

  root :to => "welcome#index"

  resources :news, :only => :index
  resources :static_pages do
    collection do
      get 'company'
      get 'devices'
      get 'partners'
      get 'help'
      get 'contact'
      get 'news'
      get 'localization'
      get 'cooperation'
      get 'technodiag'
      get 'imedia'
      get 'codes'
      get 'connectors'
      get 'cars'
    end
  end
end

app/models/code.rb
class Code < ActiveRecord::Base
   def self.search(search, page, pp)
    per_page = pp || 3
    if search
      paginate :per_page => per_page, :page => page,
               :conditions => ['number LIKE ? or text LIKE ?', "%#{search}%", "%#{search}%"],
               :order => 'number'
    else
      paginate :per_page => per_page, :page => page,
               :order => 'number'
    end
  end
end

app/models/device_photo.rb
class DevicePhoto < ActiveRecord::Base
  has_attached_file :photo,
                    :styles => { :medium => "300x300>",
                                 :thumb => "84x84>",
                                 :admin_thumb => "120x120>" },
                    :storage => :s3,
                    :s3_credentials => {:access_key_id => ENV['S3_KEY'],
                                        :secret_access_key => ENV['S3_SECRET']},
                    :bucket => "bluecheckpoint",
                    :path => ":class/:id/:style.:extension",
                    :url => ":s3_eu_url",
                    :s3_headers => { :cache_control => "max-age=#{364.days.to_i}" },
                    :s3_permissions => :public_read
end

app/models/news.rb
class News < ActiveRecord::Base

  def self.search(search, page, pp)
    per_page = pp || 3
    if search
      paginate :per_page => per_page, :page => page,
               :conditions => ['title LIKE ? or content LIKE ?', "%#{search}%", "%#{search}%"],
               :order => 'title'
    else
      paginate :per_page => per_page, :page => page,
               :order => 'title'
    end
  end
end

app/models/static_pages.rb
class StaticPages < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

  def css_class_prefix
    'admin-'
  end

  def css_id_prefix
    'admin-'
  end
end

app/controllers/admin/codes_controller.rb
class Admin::CodesController < Admin::AdminController
  def index
    @codes = Code.search(params[:q], page, 10)
  end

  def show
    @code = Code.find(params[:id])
  end

  def new
    @code = Code.new
  end

  def edit
    @code = Code.find(params[:id])
  end

  def create
    @code = Code.new(params[:code])
    if @code.save
      redirect_to(admin_code_path(@code))
    else
      render :action => :new
    end
  end

  def update
    @code = Code.find(params[:id])

    if @code.update_attributes(params[:code])
      redirect_to(admin_code_path(@code), :notice => "Code was successfully updated.")
    else
      render :action => :edit
    end
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy
    redirect_to(admin_codes_path)
  end

  private

  def page
    params[:page] || 1
  end
end

app/controllers/admin/device_photos_controller.rb
class Admin::DevicePhotosController < Admin::AdminController
  def index
    @device_photos = DevicePhoto.all
  end
  
  def new
    @device_photo = DevicePhoto.new
  end
  
  def create
  @device_photo = DevicePhoto.new(params[:device_photo])

    if @device_photo.save
      redirect_to "/admin/device_photos/"
    end
  end

  def destroy
    @device_photo = DevicePhoto.find(params[:id])
    @device_photo.destroy
    redirect_to "/admin/device_photos/"
  end

end

app/controllers/admin/maps_controller.rb
class Admin::MapsController < Admin::AdminController
  def index
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::AdminController
  def index
    @news = News.search(params[:q], page, 10)
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
  end

  def edit
    @news = News.find(params[:id])
  end

  def create
    @news = News.new(params[:news])
    if @news.save
      redirect_to(admin_news_path(@news))
    else
      render :action => :new
    end
  end

  def update
    @news = News.find(params[:id])

    if @news.update_attributes(params[:news])
      redirect_to(admin_news_path(@news), :notice => "News was successfully updated.")
    else
      render :action => :edit
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to(admin_news_index_path)
  end

  private

  def page
    params[:page] || 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "admin"
    else
      "application"
    end
  end

  def css_class_prefix
    ''
  end

  def css_id_prefix
    ''
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.paginate :per_page => 3, :page => params[:page],
                          :order => 'created_at DESC'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def company
  end

  def contact
  end

  def news
  end

  def devices
    @photos = DevicePhoto.all
  end

  def localization
  end

  def cooperation
  end

  def partners
  end

  def technodiag
  end

  def imedia
  end

  def help
  end

  def codes
  end

  def connectrs
  end

  def cars
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/codes_helper.rb
module Admin::CodesHelper
  def code_description(code)
    body = strip_tags(code.text) || ''
    body.slice(0, 30) + '...'
  end
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
  def article_description(article)
    body = strip_tags(article.content) || ''
    body.slice(0, 30) + '...'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def action_stylesheet_link_tag
    stylesheet_link_tag_if_exist File.join('app', controller_name, action_name)
  end

  def controller_stylesheet_link_tag
    stylesheet_link_tag_if_exist File.join('app', controller_name)
  end

  def action_javascript_include_tag
    javascript_include_tag_if_exist File.join('app', controller_name, action_name)
  end

  def controller_javascript_include_tag
    javascript_include_tag_if_exist File.join('app', controller_name)
  end

  def id_for_body
    "#{controller.css_id_prefix}#{controller.controller_name}-#{controller.action_name}"
  end

  def class_for_body
    "#{controller.css_class_prefix}#{controller.controller_name}"
  end

  private

  def stylesheet_link_tag_if_exist(stylesheet)
    css_file = File.join(Rails.root, 'public', 'stylesheets', stylesheet) + '.css'
    if File.exist?(css_file)
      stylesheet_link_tag stylesheet
    end
  end

  def javascript_include_tag_if_exist(javascript)
    js_file = File.join(Rails.root, 'public', 'javascripts', javascript) + '.js'
    if File.exist?(js_file)
      javascript_include_tag javascript
    end
  end

  def browser_class
    user_agent = UserAgent.parse(request.user_agent)
    return if user_agent.browser == "Internet Explorer"
    user_agent.version.to_s =~ /\A\d+\.\d+/
    return if $MATCH.blank?

    if user_agent.browser.downcase == "opera"
      user_agent.browser.downcase
    else
      user_agent.browser.downcase + $MATCH
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
  def main_article_description(article)
    body = strip_tags(article.content) || ''
    body.slice(0, 100) + '...'
  end
end

app/views/admin/codes/_form.html.erb
<%= form_for @code, :url => (@code.persisted? ? admin_code_path(@code) : admin_codes_path) do |f| %>
  <%= render 'admin/shared/error_messages', :object => f.object -%>
  <table>
    <tr>
      <td><%= f.label :number, 'Numer:' %></td>
    </tr>
      <td><%= f.text_field :number %></td>
    </tr>
    <tr>
      <td><%= f.label :text, 'Opis:', :class=>"codes-form-content" %></td>
    </tr>
      <td><%= f.text_area :text %></td>
    </tr>
    <tr>
      <td>
        <%= f.submit "Zapisz", :class => "left" %>
        <%= link_to "Cofnij", admin_codes_path, :class => "left" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/codes/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/codes/index.html.erb
<div>
  <%= form_tag admin_codes_path, :method => 'get', :id => 'codes-search-form' do %>
    <p class="search">
      <%= text_field_tag "q", nil, :placeholder => "Szukaj..." %>
    </p>
    <p id="commit">
      <%= submit_tag '' %>
    </p>
  <% end %>
  <p id="add-codes-button">
    <%= link_to "Dodaj", new_admin_code_path %>
  </p>
</div><br/><br/><br/><br/><br/>

<table id="news">
  <thead>
    <tr>
      <th class="title">Numer</th>
      <th class="content">Opis</th>
      <th class="actions">Edytuj/Usuń</th>
    </tr>
  </thead>
  <tbody>
    <% @codes.each do |c| %>
      <tr>
        <td><%= link_to c.number, admin_code_path(c)%></td>
        <td><%= code_description(c) %></td>
        <td>
          <%= link_to "Edytuj", edit_admin_code_path(c)%>
           <%= link_to "Usuń", admin_code_path(c), :method=>:delete, :class=>:destroy, :confirm=>"Napewno chcesz usunąć ?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @codes %>

app/views/admin/codes/show.html.erb
<h1>Numer:</h1>
<h2><%= @code.number %></h2>
<h1>Opis:</h1>
<div style="font-size: 16px;">
  <%= raw(@code.text) %>
</div>
<br/><br/>
<%= button_to "Edytuj", edit_admin_code_path(@code), :method => :get, :class => "left"%>
<%= button_to "Powrót", admin_codes_path, :method => :get, :class => "left" %>

app/views/admin/device_photos/_form.html.erb
<%= form_for @device_photo, :url => admin_device_photos_path, :html => { :multipart => true } do |f| %>
  <%= render 'admin/shared/error_messages', :object => f.object -%>
  <table>
    <tr>
      <td><%= f.label :name, 'Nazwa:' %></td>
    </tr>
    <tr>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :description, 'Opis:' %></td>
    </tr>
    <tr>
      <td><%= f.text_field :description %></td>
    </tr>
    <tr>
      <td>Dodaj zdjęcie:</td>
    </tr>
    <tr>
      <td>  
        <%= f.file_field :photo %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.submit "Zapisz", :class => "left" %>
        <%= link_to "Cofnij", admin_device_photos_path, :class => "left" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/device_photos/index.html.erb
<div id="device_image_add">
  <p id="add-codes-button">
    <%= link_to "Dodaj", new_admin_device_photo_path %>
  </p>
</div>
<div id="images">
  <ul>
    <% @device_photos.each do |img| %>
      <li>
        <%= image_tag(img.photo.url(:admin_thumb)) %>
        <%= link_to image_tag("/images/fancybox/fancy_close.png", :class => "remove-image"), admin_device_photo_path(img), :confirm=>"Are you sure", :method=>:delete %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/device_photos/new.html.erb
<%= render :partial => "form" %>

app/views/admin/news/_form.html.erb
<%= form_for @news, :url => (@news.persisted? ? admin_news_path(@news) : admin_news_index_path) do |f| %>
  <%= render 'admin/shared/error_messages', :object => f.object -%>
  <table>
    <tr>
      <td><%= f.label :title, 'Tytuł:' %></td>
    </tr>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td><%= f.label :content, 'Treść:', :class=>"news-form-content" %></td>
    </tr>
      <td><%= f.text_area :content %></td>
    </tr>
    <tr>
      <td>
        <%= f.submit "Zapisz", :class => "left" %>
        <%= link_to "Cofnij", admin_news_index_path, :class => "left" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/news/index.html.erb
<div>
  <%= form_tag admin_news_index_path, :method => 'get', :id => 'news-search-form' do %>
    <p class="search">
      <%= text_field_tag "q", nil, :placeholder => "Szukaj..." %>
    </p>
    <p id="commit">
      <%= submit_tag '' %>
    </p>
  <% end %>
  <p id="add-news-button">
    <%= link_to "Dodaj", new_admin_news_path %>
  </p>
</div><br/><br/><br/><br/><br/>

<table id="news">
  <thead>
    <tr>
      <th class="title">Tytuł</th>
      <th class="content">Treść</th>
      <th class="actions">Edytuj/Usuń</th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |n| %>
      <tr>
        <td><%= link_to n.title, admin_news_path(n)%></td>
        <td><%= article_description(n) %></td>
        <td>
          <%= link_to "Edytuj", edit_admin_news_path(n)%>
           <%= link_to "Usuń", admin_news_path(n), :method=>:delete, :class=>:destroy, :confirm=>"Napewno chcesz usunąć ?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @news %>

app/views/admin/news/show.html.erb
<h1>Tytuł:</h1>
<h2><%= @news.title %></h2>
<h1>Treść:</h1>
<div style="font-size: 16px;">
  <%= raw(@news.content) %>
</div>
<br/><br/>
<%= button_to "Edytuj", edit_admin_news_path(@news), :method => :get, :class => "left"%>
<%= button_to "Powrót", admin_news_index_path, :method => :get, :class => "left" %>

app/views/admin/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <p>
      <%= pluralize(object.errors.count, "error") %> prohibited this
      <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
    </p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end -%>

app/views/layouts/_admin_header.html.erb
<div id="menu">
  <div id="menu-buttons">
    <p id="news-button"
    class="<%= params[:controller] == 'admin/news' ? 'active':''%>">
      <%= link_to "NEWSY", admin_news_index_path %>
    </p>
    <p id="codes-button"
    class="<%= params[:controller] == 'admin/codes' ? 'active':''%>">
      <%= link_to "KODY", admin_codes_path %>
    </p>
    <p id="maps-button"
    class="<%= params[:controller] == 'admin/maps' ? 'active':''%>">
      <%= link_to "MAPY", admin_maps_path %>
    </p>
    <p id="images-button"
    class="<%= params[:controller] == 'admin/device_photos' ? 'active':''%>">
      <%= link_to "OBRAZKI", admin_device_photos_path %>
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="menu">
  <%= image_tag "logo_small.png", alt: 'top bar', id: 'menu-top-bar' -%>
  <div id="menu-buttons">
    <p id="pomoc-button"
    class="<%= params[:action] == 'help' || params[:action] == 'codes' || params[:action] == 'connectors' || params[:action] == 'cars' ? 'active':''%>">
      <%= link_to "", help_static_pages_path %>
    </p>
    <p id="partnerzy-button"
    class="<%= params[:action] == 'partners' || params[:action] == 'technodiag' || params[:action] == 'imedia' ? 'active':''%>">
      <%= link_to "", partners_static_pages_path %>
    </p>
    <p id="urzadzenia-button"
    class="<%= params[:action] == 'devices' || params[:action] == 'localization' || params[:action] == 'cooperation' ? 'active':''%>">
      <%= link_to "", devices_static_pages_path %>
    </p>
    <p id="firma-button"
    class="<%= params[:action] == 'company' || params[:action] == 'contact' || params[:controller] == 'news' ? 'active':''%>">
      <%= link_to "", company_static_pages_path %>
    </p>
  </div>
</div>

app/views/layouts/_subheader.html.erb
<div id="subheader">
  <% if params[:controller] == "static_pages" %>
    <% if params[:action] == "company" || params[:action] == "contact" || params[:action] == "news" %>
      <%= image_tag "layouts/company_main_line.png", alt: 'company line', id: 'main-line' -%>
      <%= image_tag "layouts/dot.png", alt: 'dot', id: 'dot' -%>
      <div class="submenu-buttons">
        <p id="kontakt-button" class="<%=  'active' if params[:action] == 'contact' %>" img-data="contact">
          <%= link_to "", contact_static_pages_path, :class=>"left"  %>
        </p>
        <p id="aktualnosci-button" img-data="news">
          <%= link_to "", news_index_path, :class=>"middle"  %>
        </p>
      </div>
    <% elsif params[:action] == "devices" || params[:action] == "localization" || params[:action] == "cooperation" %>
      <%= image_tag "layouts/devices_main_line.png", alt: 'devices line', id: 'main-line' -%>
      <%= image_tag "layouts/dot.png", alt: 'dot', id: 'dot' -%>
      <div class="submenu-buttons">
        <p id="lokalizacje-button" class="<%= 'active' if params[:action] == 'localization'%>" img-data="localization" >
          <%= link_to "", localization_static_pages_path, :class=>"left"%>
        </p>
        <p id="wspolpraca-button" class="<%= 'active' if params[:action] == 'cooperation' %>" img-data="cooperation" >
          <%= link_to "", cooperation_static_pages_path, :class=>"middle"  %>
        </p>
      </div>
    <% elsif params[:action] == "partners" || params[:action] == "technodiag" || params[:action] == "imedia" %>
      <%= image_tag "layouts/partners_main_line.png", alt: 'partners line', id: 'main-line' -%>
      <%= image_tag "layouts/dot.png", alt: 'dot', id: 'dot' -%>
      <div class="submenu-buttons">
        <p id="technodiag-button" class="<%= 'active' if params[:action] == 'technodiag'%>" img-data="technodiag" >
          <%= link_to "", "http://www.technodiag.com", :class=>"left"  %>
        </p>
        <p id="" class="not-visible">
          <%= link_to "", "", :class=>"middle"  %>
        </p>
      </div>
    <% elsif params[:action] == "help" || params[:action] == "codes" || params[:action] == "connectors" || params[:action] == "cars" %>
      <%= image_tag "layouts/help_main_line.png", alt: 'help line', id: 'main-line' -%>
      <%= image_tag "layouts/dot.png", alt: 'dot', id: 'dot-help' -%>
      <div class="submenu-buttons">
        <p id="kody-button" class="<%= 'active' if params[:action] == 'codes' %>" img-data="codes">
          <%= link_to "", codes_static_pages_path, :class=>"left" %>
        </p>
        <p id="zlacza-button" class="<%= 'active' if params[:action] == 'connectors' %>" img-data="connectors">
          <%= link_to "", connectors_static_pages_path, :class=>"middle" %>
        </p>
        <p id="samochody-button" class="<%=  'active' if params[:action] == 'cars' %>" img-data="cars">
          <%= link_to "", cars_static_pages_path, :class=>"right" %>
        </p>
      </div>
    <% end %>
  <% elsif params[:controller] == "news" %>
    <%= image_tag "layouts/company_main_line.png", alt: 'company line', id: 'main-line' -%>
    <%= image_tag "layouts/dot.png", alt: 'dot', id: 'dot' -%>
    <div class="submenu-buttons">
      <p id="kontakt-button" img-data="contact">
        <%= link_to "", contact_static_pages_path, :class=>"left"  %>
      </p>
      <p id="aktualnosci-button" class="active" img-data="news">
        <%= link_to "", news_static_pages_path, :class=>"middle"  %>
      </p>
    </div>
  <% end %>
    <div id="submenu-lines">
    <% if params[:action] == "contact" || params[:action] == "localization" || params[:action] == "technodiag" || params[:action] == "codes" %>
      <%= image_tag "layouts/submenu_line_left.png", alt: 'left line', id: 'left-line', class: "active-line" -%>
      <%= image_tag "layouts/submenu_line_middle.png", alt: 'middle line', id: 'middle-line' -%>
      <%= image_tag "layouts/submenu_line_right.png", alt: 'right line', id: 'right-line' -%>
    <% elsif params[:controller] == "news" || params[:action] == "cooperation" || params[:action] == "imedia" || params[:action] == "connectors" %>
      <%= image_tag "layouts/submenu_line_left.png", alt: 'left line', id: 'left-line' -%>
      <%= image_tag "layouts/submenu_line_middle.png", alt: 'middle line', id: 'middle-line', class: "active-line"  -%>
      <%= image_tag "layouts/submenu_line_right.png", alt: 'right line', id: 'right-line' -%>
    <% elsif params[:action] == "cars" %>
      <%= image_tag "layouts/submenu_line_left.png", alt: 'left line', id: 'left-line' -%>
      <%= image_tag "layouts/submenu_line_middle.png", alt: 'middle line', id: 'middle-line' -%>
      <%= image_tag "layouts/submenu_line_right.png", alt: 'right line', id: 'right-line', class: "active-line" -%>
    <% else %>
      <%= image_tag "layouts/submenu_line_left.png", alt: 'left line', id: 'left-line' -%>
      <%= image_tag "layouts/submenu_line_middle.png", alt: 'middle line', id: 'middle-line' -%>
      <%= image_tag "layouts/submenu_line_right.png", alt: 'right line', id: 'right-line' -%>

    <% end %>
    </div>
</div>

app/views/layouts/admin.html.erb
<!doctype html>
<%# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -%>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en" <%= yield :xml_namespace %> xmlns:bluecheckpoint="http://www.bluecheckpoint.com/ns#"> <!--<![endif]-->
<html scrolling="no">
<head>
  <meta name="google-site-verification" content="LP3ZN3Q1rdiLDdfhxwTwYONQQRmk79Wji-iqxcmt5-c" />
  <meta charset="utf-8">
  <title>Check N</title>
  <%= csrf_meta_tag %>
  <meta name="description" content="Checkn is a small privet project.">

  <%= yield :stylesheets%>
  <%# controller stylesheets can be found in app/controller_name.css -%>
  <%= controller_stylesheet_link_tag %>
  <%# action stylesheets can be found in app/controller_name/action_name.css -%>
  <%= action_stylesheet_link_tag %>
</head>
<body id="<%= id_for_body %>" class="<%= browser_class%>">
  <div id="page">
    <% if user_signed_in? %>
      <header>
        <div id="user_nav">
            Witaj  <%= current_user.email %>.
            <%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
        </div>
        <%= render :partial => "layouts/admin_header" %>
      </header>
    <% end %>
    <div id="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>


  <%= stylesheet_link_tag 'app/layouts/admin' %>
  <%= javascript_include_tag 'lib/jquery-1.5.1', 'lib/rails', 'app/admin' %>
  <%= yield :javascripts %>

</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<%# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -%>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en" <%= yield :xml_namespace %>> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en" <%= yield :xml_namespace %> xmlns:bluecheckpoint="http://www.bluecheckpoint.com/ns#"> <!--<![endif]-->
<html scrolling="no">
<head>
   <meta name="google-site-verification" content="LP3ZN3Q1rdiLDdfhxwTwYONQQRmk79Wji-iqxcmt5-c" />
  <meta charset="utf-8">
  <title>BLUE CHECK POINT</title>
  <%= csrf_meta_tag %>
  <meta name="description" content="Checkn is a small privet project.">
  <%= yield :stylesheets%>
  <%# controller stylesheets can be found in app/controller_name.css -%>
  <%= controller_stylesheet_link_tag %>
  <%# action stylesheets can be found in app/controller_name/action_name.css -%>
  <%= action_stylesheet_link_tag %>
</head>
<body id="<%= id_for_body %>" class="<%= browser_class%>">
  <div id="page">
    <header>
      <%= render :partial => "layouts/header" %>
      <%= render :partial => "layouts/subheader" %>
    </header>
    <%= render :partial => "layouts/main_circle" %>
    <div id="main">
      <%= yield %>
    </div>
  </div>


  <%= stylesheet_link_tag  'app/layouts/header', 'app/layouts/subheader', 'app/layouts/application' %>
  <%= javascript_include_tag 'lib/jquery-1.5.1', 'lib/rails', 'app/layouts/header', 'app/layouts/application'%>
  <%= yield :javascripts %>

</body>
</html>

app/views/static_pages/cars.html.erb
<div class="static">
  <p class="centered">
    Dział w budowie
  </p>
</div>
<p class="bottom-bg"></p>

app/views/static_pages/codes.html.erb
<div class="static">
  <div>
      <p class="search">
        <%= text_field_tag "q", nil, :placeholder => "Szukaj..." %>
      </p>
      <p id="commit">
        <%= submit_tag '' %>
      </p>
  </div>
</div>
<p class="bottom-bg"></p>

app/views/static_pages/connectors.html.erb
<div class="static">
  <p class="centered">
    Dział w budowie
  </p>
</div>
<p class="bottom-bg"></p>

app/views/static_pages/cooperation.html.erb
<div class="static">
  <p class="centered">
    Dział w budowie
  </p>
</div>
<p class="bottom-bg"></p>

app/views/static_pages/imedia.html.erb
<div class="static">
</div>
<p class="bottom-bg"></p>

app/views/static_pages/partners.html.erb
<div class="static">
  <p class="centered">
    Dział w budowie
  </p>
</div>
<p class="bottom-bg"></p>